name: antarctic winter sea-ice freeboard comparisons

channels:
  - conda-forge
  
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - h5py
  - netcdf4
  - pyyaml
  - cartopy
  - pip
